### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by ahundt** [logicalclocks/hops-util-py#1]
Is this ready to use and is there an example?

**Comment by jimdowling** [comment]
If you want to just try out the libraries, if you create an account here: www.hops.site, i can activate the account. Then follow the "TensorFlow tour" - there are sample hyperparameter opt notebooks (fashion_mnist), TensorFlowOnSpark, and Horovod.
If you want to install hopsworks, try it out with a vm first using:
git clone https://github.com/hopshadoop/karamel-chef.git
cd karamel-chef
./run.sh ubuntu 1 hopsworks no-random-ports

**Comment by tkakantousis** [comment]
Documentation is now available [here](https://hops.readthedocs.io/en/latest/hopsml/hopsML.html#hops-python-library).
