### ISSUE TITLE
Access featurestore from local IDE

### ISSUE THREAD

**Issue by vinayhudli** [logicalclocks/hops-util-py#152]
Hi , 
I'm trying to access feature store running on GCE and use feature store Python library from local IDE but I get this error :
session = requests.session()
NameError: name 'requests' is not defined

Is there any other way e.g. REST API to call the feature store functionality from remote as it would be really helpful instead of running code on hopsworks JupyterLab

Thanks,
Vinay

**Comment by tkakantousis** [comment]
Discussion moved to https://community.hopsworks.ai/t/accessing-hopsworks-featurestore-running-on-google-compute-engine-from-local-ide/35/4
